name: Build, Test, and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Run tests
        run: ./gradlew test
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          registry: docker.io

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "username=${{ secrets.DOCKER_HUB_USERNAME }}"
            "password=${{ secrets.DOCKER_HUB_TOKEN }}"


      - name: Debug Tags Output
        run: |
            echo "All tags: ${{ steps.meta.outputs.tags }}"
            echo "First tag: $(echo "${{ steps.meta.outputs.tags }}" | cut -d ',' -f 1)"


      - name: Update Helm chart with new image tag
        run: |
          set -e  # Exit immediately on error
          set -o pipefail  # Catch pipeline errors
          TAGS="${{ steps.meta.outputs.tags }}"
          FIRST_TAG=$(echo "$TAGS" | cut -d ',' -f 1 | tr -d '\n' | tr -d ' ')

            # Extract just the tag portion (remove registry prefix if present)
          IMAGE_TAG="${FIRST_TAG#*:}"  # Gets everything after colon
          IMAGE_TAG="${IMAGE_TAG##*/}"  # Gets everything after last slash
          
          # Update Helm values - FIXED TO USE IMAGE_TAG
          sed -i "s|tag:.*|tag: ${IMAGE_TAG}|" helm-chart/values.yaml  # Changed from ${TAG#*:}
          sed -i "s|repository:.*|repository: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}|" helm-chart/values.yaml
    
          # Configure git
          git config --global aia89 "GitHub Actions"
          git config --global user.email "${{ secrets.GIT_COMMITTER_EMAIL }}"
          
          # Commit and push changes
          git add helm-chart/values.yaml
          git commit -m "Update image tag to ${TAG#*:} [skip ci]"
          git push