name: Build, Test, and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

  # Allows manual trigger in GitHub UI
 

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository_owner }}/hello-world

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,format=long
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
    - name: Update Helm chart with new image tag
      run: |
        TAG=${{ steps.meta.outputs.tags }}
        sed -i "s|tag:.*|tag: ${TAG#*:}|" helm-chart/values.yaml
        sed -i "s|repository:.*|repository: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}|" helm-chart/values.yaml
        
        git config --global aia89 "GitHub Actions"
        git config --global aiabay.tech@gmail.com "actions@github.com"
        git add helm-chart/values.yaml
        git commit -m "Update image tag to ${TAG#*:} [skip ci]"
        git push